### ISSUE TITLE
[feature] change the size of the banner on phone

### ISSUE THREAD

**Issue by mrazarny** [HandaArchitect/obsidian-banner-snippet#8]
what i mean by the this is that on phone app alot of the pictures width are not prefect leading to most of the banners look gigantic and most of it is disappeared

![Screenshot_20240713-162236_Obsidian.png](https://github.com/user-attachments/assets/7af70584-979f-4bf6-8792-0d737790e4fb)

while it originally looks like this
![chill train snow.gif](https://github.com/user-attachments/assets/5bfbcfbd-fe92-40ad-a497-54d9fff73cfe)

**Comment by HandaArchitect** [comment]
I'll do some tweaking on the settings as I expected the image to max to full width.

**Comment by HandaArchitect** [comment]
@mrazarny I was trying to find a way for this but unfortunately cannot use CSS to calculate screen dimensions to make the banner dimensions dynamic. I made a change so that when the screen is at a max-width, the banner height is shortened by 80%.

If possible, I would recommend changing the dimensions of your banner image to a square so that it fits the banner a bit better and you would have a better view of each side. Otherwise, if you use your banner at its current dimensions and the width of the banner was adjusted to fit the width of the image, the banner would look too small, unless that is the sort of behaviour you are expecting for this?

**Comment by mrazarny** [comment]
ty for trying to help i ll just leave it like this till i learn css 

maybe i may find a solution 


overall,best banners css i have used ty

**Comment by mrazarny** [comment]
ty for trying to help i ll just leave it like this till i learn css 

maybe i may find a solution 


overall,best banners css i have used ty

**Comment by HandaArchitect** [comment]
@mrazarny please see [v1.3.1](https://github.com/HandaArchitect/obsidian-banner-snippet/releases/tag/v1.3.1). Banner height reduces by 30% on smaller screen sizes. However, a more square image would still be a better fit.
